version: '3.9'

services:
  app:
    build:
      context: .
      args:
        DEV: "true"  # Pass DEV=true during the build process
    environment:
      - DEV=true  # Set DEV as an environment variable for runtime
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
